# Generated by Django 5.1.4 on 2026-03-04 02:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
        ("cycles", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneralInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "graduation_year",
                    models.IntegerField(
                        help_text="Expected graduation year, e.g. 2027"
                    ),
                ),
                (
                    "college",
                    models.CharField(
                        help_text='College within NEU, e.g. "Khoury College of Computer Sciences"',
                        max_length=200,
                    ),
                ),
                (
                    "major",
                    models.CharField(
                        help_text='Major/program, e.g. "Computer Science"',
                        max_length=200,
                    ),
                ),
                (
                    "skills",
                    models.TextField(
                        help_text="Technical and non-technical skills (free text)."
                    ),
                ),
                (
                    "interest_areas",
                    models.TextField(
                        help_text="Areas of interest: product, engineering, design, marketing, etc."
                    ),
                ),
                (
                    "why_join",
                    models.TextField(
                        help_text="Why do you want to join NU Launch Labs?"
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="general_interests",
                        to="cycles.applicationcycle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="general_interests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "General Interest",
                "verbose_name_plural": "General Interests",
                "db_table": "general_interests",
                "ordering": ["-submitted_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "cycle"), name="unique_gi_per_user_per_cycle"
                    )
                ],
            },
        ),
    ]
