# Generated by Django 5.1.4 on 2026-03-06 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApplicationCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        help_text='Human-readable name, e.g. "Fall 2026"',
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_index=True,
                        default=True,
                        help_text="Only one cycle can be active at a time.",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Optional description or notes for this cycle.",
                    ),
                ),
                (
                    "launch_open",
                    models.BooleanField(
                        default=False,
                        help_text="When True, students can apply to Launch projects and Launch Teams can review/select candidates.",
                    ),
                ),
                (
                    "innovation_open",
                    models.BooleanField(
                        default=False,
                        help_text="When True, students can submit Innovation proposals and rank Innovation project preferences.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Application Cycle",
                "verbose_name_plural": "Application Cycles",
                "db_table": "application_cycles",
                "ordering": ["-created_at"],
            },
        ),
    ]
