# Generated by Django 5.1.4 on 2026-03-19 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cycles", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "track",
                    models.CharField(
                        choices=[("LAUNCH", "Launch"), ("INNOVATION", "Innovation")],
                        help_text="LAUNCH or INNOVATION",
                        max_length=20,
                    ),
                ),
                (
                    "innovation_project_id_placeholder",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Placeholder for InnovationProject ID. Becomes FK in Phase 4.",
                        null=True,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments_made",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="cycles.applicationcycle",
                    ),
                ),
            ],
            options={
                "verbose_name": "Assignment",
                "verbose_name_plural": "Assignments",
                "db_table": "assignments",
                "ordering": ["-assigned_at"],
            },
        ),
    ]
