# Generated by Django 5.1.4 on 2026-03-26 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cycles", "0003_assignment_launch_project_assignment_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="assignment",
            name="innovation_project_id_placeholder",
        ),
    ]
