# Generated by Django 5.1.4 on 2026-03-26 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cycles", "0004_remove_assignment_innovation_project_id_placeholder"),
        ("innovation", "0001_initial"),
        ("launch", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="assignment",
            name="innovation_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments",
                to="innovation.innovationproject",
            ),
        ),
        migrations.AddConstraint(
            model_name="assignment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("innovation_project__isnull", True),
                        ("launch_project__isnull", False),
                    ),
                    models.Q(
                        ("innovation_project__isnull", False),
                        ("launch_project__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="exactly_one_project_assigned",
            ),
        ),
    ]
