# Generated by Django 5.1.4 on 2026-03-19 21:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cycles", "0002_assignment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LaunchProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Title of Launch Project", max_length=200
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of Launch Project"),
                ),
                (
                    "requirements",
                    models.TextField(
                        blank=True,
                        help_text='Requirements for application to project, e.g., "proficiency with Django"',
                        null=True,
                    ),
                ),
                ("max_members", models.IntegerField(default=4)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="launch_projects",
                        to="cycles.applicationcycle",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="launch_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Launch Project",
                "verbose_name_plural": "Launch Projects",
                "db_table": "launch_projects",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LaunchApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "resume",
                    models.CharField(
                        blank=True,
                        help_text="Link to applicant's resume",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "portfolio",
                    models.CharField(
                        blank=True,
                        help_text="Link to applicant's portfolio",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "responses",
                    models.JSONField(
                        blank=True, help_text="Responses to application", null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("FILTERED", "Filtered"),
                            ("SENT_TO_TEAM", "Sent to team"),
                            ("SELECTED", "Selected"),
                            ("NOT_SELECTED", "Not selected"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="SUBMITTED",
                        help_text="The status of the application, e.g., Submitted, Selected, etc",
                        max_length=20,
                    ),
                ),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="launch_applications",
                        to="cycles.applicationcycle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="launch_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="launch_applications",
                        to="launch.launchproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Launch Application",
                "verbose_name_plural": "Launch Applications",
                "db_table": "launch_applications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LaunchCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_REVIEW", "Pending review"),
                            ("SELECTED", "Selected"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="PENDING_REVIEW",
                        help_text="The status of the candidate, e.g., Selected, Rejected, etc",
                        max_length=20,
                    ),
                ),
                (
                    "selected_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="The DateTime a candidate is selected for a given project",
                        null=True,
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="launch_candidates",
                        to="launch.launchapplication",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="launch_candidates",
                        to="launch.launchproject",
                    ),
                ),
            ],
            options={
                "verbose_name": "Launch Candidate",
                "verbose_name_plural": "Launch Candidates",
                "db_table": "launch_candidates",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("application", "project"),
                        name="unique_lc_per_application_per_project",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="launchapplication",
            constraint=models.UniqueConstraint(
                fields=("user", "project", "cycle"),
                name="unique_la_per_user_per_project_per_cycle",
            ),
        ),
    ]
