# Generated by Django 5.1.4 on 2026-03-26 02:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cycles", "0004_remove_assignment_innovation_project_id_placeholder"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Proposals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(help_text="Title of Proposal", max_length=200),
                ),
                (
                    "description",
                    models.TextField(help_text="Description of proposed project"),
                ),
                (
                    "tech_stack",
                    models.TextField(
                        blank=True,
                        help_text="Tech stack to use for this proposed project",
                        null=True,
                    ),
                ),
                ("max_members", models.IntegerField(default=4)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUBMITTED", "Submitted"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                        ],
                        default="SUBMITTED",
                        help_text="The status of the proposal, e.g., Submitted, Approved, etc",
                        max_length=20,
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to="cycles.applicationcycle",
                    ),
                ),
                (
                    "proposer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proposals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Innovation Proposal",
                "verbose_name_plural": "Innovation Proposals",
                "db_table": "proposals",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="InnovationProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("max_members", models.IntegerField(default=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="innovation_projects",
                        to="cycles.applicationcycle",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="led_innovation_projects",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "proposal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="innovation_project",
                        to="innovation.proposals",
                    ),
                ),
            ],
            options={
                "db_table": "innovation_projects",
            },
        ),
        migrations.CreateModel(
            name="InnovationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rank", models.IntegerField(choices=[(1, "1"), (2, "2"), (3, "3")])),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="innovation_preferences",
                        to="cycles.applicationcycle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="innovation_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to="innovation.innovationproject",
                    ),
                ),
            ],
            options={
                "db_table": "innovation_preferences",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "project", "cycle"),
                        name="unique_user_project_cycle",
                    ),
                    models.UniqueConstraint(
                        fields=("user", "rank", "cycle"), name="unique_user_rank_cycle"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rank__in", [1, 2, 3])),
                        name="rank_must_be_1_2_or_3",
                    ),
                ],
            },
        ),
    ]
