# Generated by Django 5.1.4 on 2026-03-06 04:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("USER_REGISTERED", "User Registered"),
                            ("LAUNCH_TEAM_CREATED", "Launch Team Created"),
                            ("GI_SUBMITTED", "General Interest Submitted"),
                            ("GI_UPDATED", "General Interest Updated"),
                            ("ROLE_CHANGED", "Role Changed"),
                            ("PASSWORD_CHANGED", "Password Changed"),
                            ("CYCLE_CREATED", "Cycle Created"),
                            ("CYCLE_TOGGLES_UPDATED", "Cycle Toggles Updated"),
                            ("CYCLE_CLOSED", "Cycle Closed"),
                            ("LAUNCH_PROJECT_CREATED", "Launch Project Created"),
                            ("LAUNCH_PROJECT_DELETED", "Launch Project Deleted"),
                            ("LAUNCH_APP_SUBMITTED", "Launch Application Submitted"),
                            ("CANDIDATE_SENT_TO_TEAM", "Candidate Sent to Team"),
                            ("CANDIDATE_SELECTED", "Candidate Selected"),
                            (
                                "LAUNCH_SELECTION_CONFIRMED",
                                "Launch Selection Confirmed",
                            ),
                            ("PROPOSAL_SUBMITTED", "Proposal Submitted"),
                            ("PROPOSAL_APPROVED", "Proposal Approved"),
                            ("PROPOSAL_REJECTED", "Proposal Rejected"),
                            (
                                "INNOVATION_PROJECT_DELETED",
                                "Innovation Project Deleted",
                            ),
                            ("PREFERENCES_SUBMITTED", "Preferences Submitted"),
                            ("INNOVATION_ASSIGNED", "Innovation Assigned"),
                            ("ASSIGNMENT_REMOVED", "Assignment Removed"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "target_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text='The model type affected, e.g. "User", "ApplicationCycle".',
                        max_length=50,
                    ),
                ),
                (
                    "target_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="The primary key of the affected record.",
                        null=True,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Action-specific details (flexible key-value).",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP address of the request that triggered this action.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        help_text="The user who performed the action.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["action", "created_at"],
                        name="audit_logs_action_391715_idx",
                    ),
                    models.Index(
                        fields=["actor", "created_at"],
                        name="audit_logs_actor_i_5bd818_idx",
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="audit_logs_target__9fc8de_idx",
                    ),
                ],
            },
        ),
    ]
