# Generated by Django 5.1.4 on 2026-03-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("USER_REGISTERED", "User Registered"),
                    ("LAUNCH_TEAM_CREATED", "Launch Team Created"),
                    ("GI_SUBMITTED", "General Interest Submitted"),
                    ("GI_UPDATED", "General Interest Updated"),
                    ("ROLE_CHANGED", "Role Changed"),
                    ("PASSWORD_CHANGED", "Password Changed"),
                    ("CYCLE_CREATED", "Cycle Created"),
                    ("CYCLE_TOGGLES_UPDATED", "Cycle Toggles Updated"),
                    ("CYCLE_CLOSED", "Cycle Closed"),
                    ("LAUNCH_PROJECT_CREATED", "Launch Project Created"),
                    ("LAUNCH_PROJECT_DELETED", "Launch Project Deleted"),
                    ("LAUNCH_APPLICATION_SUBMITTED", "Launch Application Submitted"),
                    ("LAUNCH_APPLICATION_FILTERED", "Launch Application Filtered"),
                    ("LAUNCH_SENT_TO_TEAM", "Launch Sent to Team"),
                    ("LAUNCH_CANDIDATE_SELECTED", "Launch Candidate Selected"),
                    ("LAUNCH_CANDIDATE_REJECTED", "Launch Candidate Rejected"),
                    ("PROPOSAL_SUBMITTED", "Proposal Submitted"),
                    ("PROPOSAL_APPROVED", "Proposal Approved"),
                    ("PROPOSAL_REJECTED", "Proposal Rejected"),
                    ("INNOVATION_PROJECT_DELETED", "Innovation Project Deleted"),
                    ("PREFERENCES_SUBMITTED", "Preferences Submitted"),
                    ("INNOVATION_ASSIGNED", "Innovation Assigned"),
                    ("ASSIGNMENT_REMOVED", "Assignment Removed"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
